[package]
name = "rpo-optimizer"
version = "0.1.0"
edition = "2021"
authors = ["Gabriel Demetrios Lafis"]

[dependencies]
nalgebra = { workspace = true }
statrs = { workspace = true }
log = { workspace = true }



rand = { workspace = true }
