[package]
name = "rpo-utils"
version = "0.1.0"
edition = "2021"
authors = ["Gabriel Demetrios Lafis"]

[dependencies]
log = { workspace = true }
env_logger = { workspace = true }
plotters = { workspace = true }



anyhow = { workspace = true }
